import assert from 'node:assert/strict';
import fs from 'node:fs';
assert.ok(fs.existsSync(new URL('../.qiji-xiha888-sandbox', import.meta.url)));
let calls = [], reply = {code:200,data:{task_id:123456}}, http = 200, network = false;
globalThis.fetch = async (url, init) => { calls.push({url:String(url),...init}); if(network) throw Error('offline'); return new Response(JSON.stringify(reply), {status:http}); };
const {getModelDef,listModels} = await import('../src/store/models.ts');
const {getChannel} = await import('../src/store/channels.ts');
const {getMode} = await import('../src/store/modes.ts');
const {isBuiltinProtocol} = await import('../src/store/protocols.ts');
const {resolveUpstream} = await import('../src/translators/upstream.ts');
const {imageUpstreamParams} = await import('../src/imageRouting.ts');
const m = getModelDef('xiha888-mj-imagine');
assert.equal(m.protocol,'xiha888-image'); assert.equal(m.upstreamModel,'mj_imagine');
assert.equal(m.enabled,false); assert.equal(m.shareScope,'none'); assert.equal(m.matLimits?.img,undefined);
assert.equal(m.familyId,'fam-mj'); assert.equal(getChannel(m.channelId).name,'xiha888');
assert.equal(getMode('xiha888').name,'xiha888'); assert.ok(isBuiltinProtocol(m.protocol));
assert.equal(resolveUpstream(m).baseUrl,'https://api.lk888.ai');
assert.deepEqual(imageUpstreamParams(m,{aspect_ratio:'4:5',quality:'2'}),{aspect_ratio:'4:5',aspectRatio:'4:5',quality:'2'});
assert.deepEqual(imageUpstreamParams(m,{}),{});
const retained = new URL('../retained.json',import.meta.url);
if(fs.existsSync(retained)) assert.deepEqual(listModels().filter(x=>x.id!==m.id),JSON.parse(fs.readFileSync(retained)));
if(process.argv[2]==='seed') { console.log('xiha888 seed and retained model checks passed'); process.exit(0); }
const {submitXiha888Image:submit,pollXiha888Image:poll} = await import('../src/translators/xiha888.ts');
const up = {baseUrl:'https://api.lk888.ai/v1/',apiKey:'sk-test-xiha888-secret',upstreamModel:'mj_imagine'};
const req = {model:m.id,purpose:'image.generate',promptOverride:'cat "test"',params:{botType:'NIJI_JOURNEY',aspectRatio:'21:9',quality:'0.5',stylize:0,style:'',extra:{keep:true},notify_url:'https://callback.example/task'},inputs:{images:Array.from({length:6},(_,i)=>({url:`https://ref.example/${i}.png`}))}};
const original = structuredClone(req), logs=[];
assert.deepEqual(await submit(req,up,x=>logs.push(x)),{ok:true,taskId:'123456'});
const sent=JSON.parse(calls.at(-1).body);
assert.equal(calls.at(-1).url,'https://api.lk888.ai/v1/media/generate');
assert.equal(calls.at(-1).headers.Authorization,'Bearer '+up.apiKey);
assert.equal(sent.params.images.length,6); assert.equal(sent.params.botType,'NIJI_JOURNEY');
assert.equal(sent.notify_url,req.params.notify_url); assert.equal(sent.params.notify_url,undefined);
assert.deepEqual(sent.params.extra,{keep:true}); assert.equal(sent.params.stylize,0); assert.equal(sent.params.style,'');
assert.equal(sent.prompt,req.promptOverride); assert.deepEqual(req,original); assert.ok(!JSON.stringify(logs).includes(up.apiKey));
await submit({...req,params:{}},up); assert.equal(JSON.parse(calls.at(-1).body).params.botType,'MID_JOURNEY');
assert.equal(JSON.parse(calls.at(-1).body).params.aspectRatio,'1:1');
reply={code:400,msg:'余额不足'}; assert.equal((await submit(req,up)).error,'余额不足');
reply={code:200,data:{}}; assert.equal((await submit(req,up)).ok,false);
const count=calls.length; assert.equal((await submit(req,{...up,apiKey:''})).ok,false); assert.equal(calls.length,count);
for(const final of [false,undefined,'true']) {reply={state:'success',is_final:final,result_url:'https://cdn.example/image.png',progress:'45%'}; const r=await poll(up,'a&b'); assert.equal(r.status,'running'); assert.equal(r.progress,45);}
assert.ok(calls.at(-1).url.endsWith('task_id=a%26b'));
reply={state:'pending',is_final:false,status:'已完成'};assert.equal((await poll(up,'1')).status,'queued');
reply={state:'failed',is_final:false,error:'wait'}; assert.equal((await poll(up,'1')).status,'running');
reply={state:'failed',is_final:true,error:'审核未通过'}; assert.equal((await poll(up,'1')).error,'审核未通过');
reply={state:'success',is_final:true,result_url:'https://cdn.example/out.mp4',result_type:'image'};
assert.deepEqual(await poll(up,'1'),{status:'completed',videoUrl:reply.result_url});
assert.equal((await poll(up,'1')).resultHeaders,undefined);
reply={state:'success',is_final:true}; assert.equal((await poll(up,'1')).status,'failed');
reply={state:'new_state',is_final:true}; assert.equal((await poll(up,'1')).status,'running');
for(const status of [429,500,503]) {http=status; assert.equal((await poll(up,'1')).status,'running');}
http=401; assert.equal((await poll(up,'1')).status,'failed'); http=200; network=true; assert.equal((await poll(up,'1')).status,'running');
const html=fs.readFileSync(new URL('../src/admin/index.html',import.meta.url),'utf8');
for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g)) new Function(match[1]);
assert.ok(html.includes('"xiha888-image"'));
console.log('xiha888 protocol, seed, admin syntax and preservation checks passed; zero live upstream calls');
